FROM node:18.7.0-alpine3.15 AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN node test-resource-inheritance.cjs
RUN node test-bulk-push.cjs
RUN node test-radio-enable.cjs
RUN npm run build

FROM openwifi-owprov-ui:shinesystems-20260930 AS runtime
COPY --from=build /app/build/ /usr/share/nginx/html/
